package com.cblue.oa.entity;

import java.util.Date;
import java.util.HashSet;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Apply.java
//  @ Date : 2017/12/15
//  @ Author : 
//
//
import java.util.Set;




public class Apply {
	
	public static final String STATUS_RUNNING="审核中";
	public static final String STATUS_OK="通过审核";
	public static final String STATUS_LOSER="审核失败";
	
	
	private Long id;
	private String filePath;
	private String title;
	private User applyUser;
	private Date applyDate;
	private String applyStatus;
	private Template template;
	private Set<Check> checks = new HashSet<Check>();
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getFilePath() {
		return filePath;
	}
	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public User getApplyUser() {
		return applyUser;
	}
	public void setApplyUser(User applyUser) {
		this.applyUser = applyUser;
	}
	public Date getApplyDate() {
		return applyDate;
	}
	public void setApplyDate(Date applyDate) {
		this.applyDate = applyDate;
	}
	public String getApplyStatus() {
		return applyStatus;
	}
	public void setApplyStatus(String applyStatus) {
		this.applyStatus = applyStatus;
	}
	public Template getTemplate() {
		return template;
	}
	public void setTemplate(Template template) {
		this.template = template;
	}
	public Set<Check> getChecks() {
		return checks;
	}
	public void setChecks(Set<Check> checks) {
		this.checks = checks;
	}
	
	
}
