package com.cblue.oa.entity;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Forum.java
//  @ Date : 2017/11/30
//  @ Author : 
//
//




public class ForumManage {
	private Long id;
	private String name;
	private String description;
	private Long position;
	private Long themeCount;
	private Long replyCount;
	private Theme lastTheme;
	
	public Long getThemeCount() {
		return themeCount;
	}
	public void setThemeCount(Long themeCount) {
		this.themeCount = themeCount;
	}
	public Long getReplyCount() {
		return replyCount;
	}
	public void setReplyCount(Long replyCount) {
		this.replyCount = replyCount;
	}
	public Theme getLastTheme() {
		return lastTheme;
	}
	public void setLastTheme(Theme lastTheme) {
		this.lastTheme = lastTheme;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Long getPosition() {
		return position;
	}
	public void setPosition(Long position) {
		this.position = position;
	}
	
	
}
