package com.cblue.oa.entity;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reply.java
//  @ Date : 2017/12/1
//  @ Author : 
//
//




public class Reply extends Article {
	private int isShow;
	private Theme theme;
	public int getIsShow() {
		return isShow;
	}
	public void setIsShow(int isShow) {
		this.isShow = isShow;
	}
	public Theme getTheme() {
		return theme;
	}
	public void setTheme(Theme theme) {
		this.theme = theme;
	}
	
}
