package com.cblue.oa.entity;

import java.util.HashSet;
import java.util.Set;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Theme.java
//  @ Date : 2017/12/1
//  @ Author : 
//
//




public class Theme extends Article {
	private String title;
	private Long replyCount;
	private Reply lastReply;
	private int type;
	private ForumManage forumManage;
	private Set<Reply> replys = new HashSet<Reply>();
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public Long getReplyCount() {
		return replyCount;
	}
	public void setReplyCount(Long replyCount) {
		this.replyCount = replyCount;
	}
	public Reply getLastReply() {
		return lastReply;
	}
	public void setLastReply(Reply lastReply) {
		this.lastReply = lastReply;
	}
	public int getType() {
		return type;
	}
	public void setType(int type) {
		this.type = type;
	}
	public ForumManage getForumManage() {
		return forumManage;
	}
	public void setForumManage(ForumManage forumManage) {
		this.forumManage = forumManage;
	}
	public Set<Reply> getReplys() {
		return replys;
	}
	public void setReplys(Set<Reply> replys) {
		this.replys = replys;
	}
	
	
}
