package com.cblue.oa.entity;

import java.util.HashSet;
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 2017/11/20
//  @ Author : 
//
//
import java.util.Set;




public class User {
	private Long id;
	private String loginName;
	private String password;
	private String name;
	private int sex;
	private String phone;
	private String email;
	private String description;
	private Department department;
	private Set<Role> roles = new HashSet<Role>();
	
	
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getLoginName() {
		return loginName;
	}
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getSex() {
		return sex;
	}
	public void setSex(int sex) {
		this.sex = sex;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Department getDepartment() {
		return department;
	}
	public void setDepartment(Department department) {
		this.department = department;
	}
	public Set<Role> getRoles() {
		return roles;
	}
	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}
	
	/**
	 * 判断是否是超级管理员
	 */
	public boolean isAdmin(){
		return "admin".equals(getLoginName());
	}
	
	/**
	 * 判断是否有权限
	 */
	 public boolean hasPrivilegeByName(String name){
		if(isAdmin()){
			return true;
		}
		Set<Role> roles =  getRoles();
		for(Role role:roles){
			Set<Privilege> privileges = role.getPrivileges();
			for(Privilege privilege:privileges){
				if(privilege.getName().equals(name)){
					return true;
				}
			}
		}
		return false;
	 }
	 
	 public boolean hasPrivilegeByUrl(String url){
		   if(isAdmin()){
				return true;
			}
			Set<Role> roles =  getRoles();
			for(Role role:roles){
				Set<Privilege> privileges = role.getPrivileges();
				for(Privilege privilege:privileges){
					if(url.equals(privilege.getUrl())){
						return true;
					}
				}
			}
			return false;
		 }
	
	
	
}
